# Generated by Django 3.2.9 on 2022-01-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_provider_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='description',
            new_name='name',
        ),
    ]
